
// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// misc
export const OPEN_PROBLEM_DRAWER = "OPEN_PROBLEM_DRAWER";
export const CLOSE_PROBLEM_DRAWER = "CLOSE_PROBLEM_DRAWER";